# -*- mode: ruby -*-
# vi: set ft=ruby:
home = ENV['HOME']

MACHINES = {
  :'control' => {
      :box_name => "ubuntu/focal64",
      :box_url => "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64-vagrant.box",
      :box_cpu => "4",
      :box_mem => "16256",
      :priv_ip_addr => '192.168.56.201',
      :pub_ip_addr => '192.168.0.121',
    },
  :'node1' => {
      :box_name => "ubuntu/focal64",
      :box_url => "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64-vagrant.box",
      :pub_ip_addr => '192.168.0.122',
  },
  :'node2' => {
      :box_name => "ubuntu/focal64",
      :box_url => "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64-vagrant.box",
      :pub_ip_addr => '192.168.0.123',
  }  

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
        
          box.vm.box_check_update = false

          box.vm.box = boxconfig[:box_name]
          box.vm.box_url  = boxconfig[:box_url]
          box.vm.host_name = boxname.to_s

          # box.vm.network "private_network", ip:boxconfig[:priv_ip_addr]
          box.vm.network "public_network", bridge: "enp5s0", ip:boxconfig[:pub_ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.name = boxname.to_s
            vb.customize ["modifyvm", :id, "--memory", boxconfig[:box_mem] || 1024 ]
            vb.customize ["modifyvm", :id, "--cpus", boxconfig[:box_cpu] || 1 ]
          end
          
          if box.vm.hostname == "control" 
            box.vm.provision "shell", inline: <<-SHELL
              sudo apt update
              sudo apt -y install nginx python3-pip ansible sshpass
              sudo ln -s /usr/bin/python3 /usr/bin/python
              sudo pip install ansible-cmdb
            SHELL
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
            sudo service sshd restart
            echo -e "vagrant\nvagrant" | sudo passwd vagrant 
          SHELL
      end
    end
      config.vm.synced_folder "share/", "/vagrant/share"
end
